#%RAML 1.0
title: Major Assignment - Rajat Upadhyay
baseUri: http://majorassignmentday5rajatmilestone2-dteu.us-e2.cloudhub.io
description: Request the flow created in milestone 2 part 2.
mediaType:
  - application/json
protocols:
  - HTTP
types:
  Milestone2ResponseDataType:
    items:
      example:
        strict: true
        value:
          id: 3817
          name: The Hon. Bankim Bandopadhyay
          email: the_bandopadhyay_bankim_hon@boyle-robel.name
          gender: female
          status: inactive
      properties:
        id:
          example: 1
          type: number
          format: int
        name:
          example: Example
          type: string
        email:
          example: Example
          type: string
        gender:
          example: Example
          type: string
        status:
          example: Example
          type: string
/milestone1:
  get:
    body: {}
    responses:
      "200":
        body:
          type: Milestone2ResponseDataType
          items:
            type: object
    securedBy: []
